// LOGIN ACTIONS
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// PRESENTATION ACTIONS
export const PRESENTATION_REQUEST = 'PRESENTATION_REQUEST';
export const PRESENTATION_SUCCESS = 'PRESENTATION_SUCCESS';
export const PRESENTATION_FAILURE = 'PRESENTATION_FAILURE';

// CONTROL PANEL SIDE MENU OPTIONS
export const SHOW_ADMIN_USERS_OPTIONS = 'SHOW_ADMIN_USERS_OPTIONS';
export const SHOW_VISUAL_SETTINGS_OPTIONS = 'SHOW_VISUAL_SETTINGS_OPTIONS';
export const SHOW_MENU_ADMIN_OPTIONS = 'SHOW_MENU_ADMIN_OPTIONS';
export const SHOW_ADD_PICTURE_TEXT_OPTIONS = 'SHOW_ADD_PICTURE_TEXT_OPTIONS';
export const SHOW_MANAGE_PRESENTATION_OPTIONS =
	'SHOW_MANAGE_PRESENTATION_OPTIONS';
export const SHOW_FAQ_OPTIONS = 'SHOW_FAQ_OPTIONS';

// MENU ADMIN SECTION
export const NUMBER_CATEGORY_SELECT = 'NUMBER_CATEGORY_SELECT';
